wip -- hybrid mode and minor edits
This commit mainly handles the hybrid mode: a node having a local
disk partition containing a directory named 'walt-hybrid' will
boot using the hybrid mode. This means during walt-init the image
will be copied locally on this disk and the node will complete its
bootup procedure by booting from it.
This can be useful when the network boot mode and its RAM overlay
does not fit a given situation (for instance, if the node should
acts as a kubernetes node and download OS images locally).

The walt-init scripts were largely refactored.

This change also caused various changes about reboots and virtual
nodes, because without the RAM overlay trick, hybrid boot requires
proper OS shutdown when rebooting, with or without kexec.

* Changes in walt-virtual-node, mainly to handle config changes
(e.g. disk change) and the effect of reboots properly.
-> walt-virtual-node can now work with two modes:
   - "unmanaged", the legacy mode. In this mode, the python process
     just starts the qemu VM and then wait() on its pid. stdin is
     directly handled by the qemu VM process. From now on, this mode
     will only be used for VPN nodes.
   - "managed". In this mode, the python process waits for data on
     stdin, and, if the qemu VM is started, on a PID fd created to
     monitor it, by using select.poll(). On stdin, walt-server-daemon
     can send INPUT data for the VM or commands to KILL it, change
     its CONFiguration (disks, networks, cpu, etc.),
     and EXIT walt-virtual-node (when walt-server-daemon ends).
-> when vnode settings are updated, send corresponding CONF commands.
-> when rebooting a vnode, do it preferably by a REBOOT command to
   walt-net-service, so that proper shutdown can be done in case
   of hybrid boot.
-> if hard-rebooting send a KILL_VM command to walt-virtual-node.
-> when walt-server-daemon ends, send EXIT to walt-virtual-node.

* init scripts now look for /bin/walt-network-reboot and
  /bin/walt-hybrid-reboot. For compatibility with old images
  /bin/walt-reboot is detected too as a fallback if the boot mode
  is network and walt-network-reboot is missing.

* In our default debian PC images, all these reboot commands
  are symlinks to /usr/bin/walt-ipxe-kexec-reboot (provided by
  walt-node module, as before), and this python code checks
  the env var "walt_boot_mode" exported by the caller code
  of walt-init.

* In walt-net-service, disable the use of /bin/walt-*-reboot if the
  node is virtual (check if /sys/class/dmi/id/sys_vendor is QEMU).
  This is because restarting virtual nodes is fast, so using
  walt-reboot is not useful, and VM config changes need the qemu VM
  process itself to be restarted, which would not be the case if
  kexec is used.

* In walt-script-common, if hybrid boot (env var), perform a reboot
  with proper shutdown of the OS. In walt-ipxe-kexec-reboot (walt-node
  module), only run "kexec -e" directly if the mode if "network boot"
  (given by env var too). Otherwise, load the kexec kernel (kexec -l)
  but just call "reboot". At the end of OS shutdown, a last service
  should detect a kexec kernel has been loaded and perform the
  "kexec -e" itself.

All the above is done.
Remaining:
* walt-reboot -> walt-network-reboot + walt-hybrid-reboot, ça marche ?
* doc (node-reboot, vnode-disks, boot-modes)
* make test

diff --git a/server/walt/server/processes/main/images/walt-net-service b/server/walt/server/processes/main/images/walt-net-service
--- a/server/walt/server/processes/main/images/walt-net-service
+++ b/server/walt/server/processes/main/images/walt-net-service
@@ -1,49 +1,31 @@
 #!/bin/sh
-set -e
+. /bin/walt-script-common --catch-errors
 MSG_NO_BLINK_EXEC='/bin/blink unavailable or not executable on image'
 MSG_BLINK_FAILED='/bin/blink returned a non-zero error code'
-MSG_WALT_REBOOT_NO_EXEC='/bin/walt-reboot is not executable on image'
 
-final_root="$1"
+final_root="/mnt/fs_final"
 
-
-on_exit()
-{
-    echo "[bg] walt-net-service exited! What happened?? Let's reboot!"
-    sleep 5
-    reboot -f
-}
-
-trap on_exit EXIT
 echo "[bg] walt-net-service started."
 
-# create fifos to communicate with the nc process
-fifo_in=$(mktemp -u); mkfifo $fifo_in
-fifo_out=$(mktemp -u); mkfifo $fifo_out
+# create a fifo
+fifo_server_to_node=$(mktemp -u); mkfifo $fifo_server_to_node
 
-# start the nc process in the background
-# to communicate with the server
-while [ 1 ]
-do
-    busybox nc -l -p %(walt_node_net_service_port)s
-done < $fifo_out > $fifo_in &
+timely_input() {
+    while true
+    do
+        if ! wait_for_input_line_shortly $1
+        then
+            # send notification message on fd 7
+            echo "SHELL-TIMEOUT" >&7
+            return 1
+        fi
+    done
+}
 
-# pipe fd 5 to standard output of nc (we will read
-# requests from the server there)
-# pipe fd 6 to standard input of nc (we will send
-# results there)
-exec 6>$fifo_out 5<$fifo_in
-
-do_walt_reboot() {
-    cd "$final_root"
-    echo "Calling bin/walt-reboot"
-    chroot . bin/walt-reboot
-    # if we are here, this means bin/walt-reboot failed
-    # to reboot the OS.
-    echo -n "Command 'bin/walt-reboot' failed. "
-    echo "Falling back to standard 'reboot -f'."
-    cd /
-    reboot -f
+shell_with_timeout() {
+    exec 7>&1
+    timely_input 15 | busybox sh -i 2>&1 || true
+    exec 7>&-
 }
 
 # Caution with optional files /bin/walt-reboot & /bin/blink:
@@ -56,55 +38,178 @@ do_walt_reboot() {
 # chroot "$final_root" [ -e "/bin/walt-reboot" ]
 # is the correct expression.
 
-# loop and handle coming requests
-while read req args <&5
+# Some versions of nc only close when there stdin is closed.
+# the remote peer closing the connection is not enough, and
+# could cause the "nc -l" process to block (with its socket
+# in TCP CLOSE_WAIT state). In this case, walt-net-service
+# is completely unusable: the code will not accept new
+# connections.
+# In this code, we force nc to close by using a command
+# `<proc> | nc -l` and let <proc> stop when needed.
+
+# The walt server uses one short-lived connection for each
+# request. This is the mode named "single" below. In this mode
+# <proc> stops after having processed each request.
+
+# Another use of this service is for debugging:
+# $ nc <node-ip> 12346
+# MODE multi
+# PING
+# OK
+# SHELL
+# OK
+# ...
+# CLOSE
+# In this mode named "multi", the server handles several
+# contiguous requests on the same connection.
+# As mentionned above, there is a risk of blocking the "nc -l"
+# process if the user forgets to run CLOSE.
+# To avoid this, we implement a timeout when reading requests
+# in this mode.
+# We also implement a timeout for SHELL command inputs.
+# Note: unfortunately, there may still be ways to block the
+# process such as letting a command such as "busybox top" run
+# indefinitely in a SHELL session.
+
+is_vnode() {
+    if [ -r "/sys/class/dmi/id/sys_vendor" ]
+    then
+        sys_vendor="$(cat "/sys/class/dmi/id/sys_vendor")"
+        if [ "$sys_vendor" = "QEMU" ]
+        then
+            return 0  # yes, vnode
+        fi
+    fi
+    return 1  # no, not a vnode
+}
+
+get_custom_walt_reboot_script() {
+    # custom rebooting is disabled for virtual nodes
+    if is_vnode
+    then
+        return
+    fi
+    if [ "${walt_boot_mode}" = "network" ]
+    then
+        # /bin/walt-network-reboot (new image)
+        if chroot "$final_root" [ -e "/bin/walt-network-reboot" ]; then
+            echo "/bin/walt-network-reboot"
+            return
+        fi
+        # legacy /bin/walt-reboot (old image)
+        if chroot "$final_root" [ -e "/bin/walt-reboot" ]; then
+            echo "/bin/walt-reboot"
+            return
+        fi
+    else    # hybrid boot
+        # /bin/walt-hybrid-reboot (new image)
+        if chroot "$final_root" [ -e "/bin/walt-hybrid-reboot" ]; then
+            echo "/bin/walt-hybrid-reboot"
+            return
+        fi
+        # note: hybrid boot is unknown for old images
+    fi
+}
+
+# loop and handle incoming requests
+_handle_one_connection() {
+    mode="unknown"
+    while true
+    do
+        if [ "$mode" = "multi" ]
+        then
+            # timeout if no more input on the connection
+            if line=$(wait_for_input_line_shortly 15)
+            then
+                set -- $line
+                req="$1"; shift; args="$@"
+            else
+                echo "TIMEOUT Closing on my side."
+                break
+            fi
+        else
+            read req args
+        fi
+
+        if [ "$req" = "CLOSE" ]; then echo "OK Closing on my side."; break; fi
+
+        if [ "$req" = "MODE" ]
+        then
+            mode=$args
+            continue
+        else
+            if [ "$mode" = "unknown" ]
+            then
+                echo KO 'Start by specifying "MODE [single|multi]". Closing on my side.'
+                break
+            fi
+        fi
+
+        # respond to server if it checks whether we are alive
+        if [ "$req" = "PING" ]; then echo OK; fi
+
+        # respond to DMESG requests
+        if [ "$req" = "DMESG" ]; then echo OK; echo; busybox dmesg; fi
+
+        # respond to SHELL requests
+        if [ "$req" = "SHELL" ]; then
+            echo OK; echo
+            shell_with_timeout
+            echo END-OF-SHELL
+        fi
+
+        # reboot the node when we receive REBOOT
+        if [ "$req" = "REBOOT" ]; then
+            custom_script=$(get_custom_walt_reboot_script)
+            if [ ! -z "$custom_script" ]
+            then
+                # try to run it
+                if chroot "$final_root" [ -x "$custom_script" ]; then
+                    echo OK
+                    trigger_walt_reboot walt-custom-reboot $custom_script
+                else
+                    echo KO $custom_script is not executable on image
+                fi
+            else
+                echo OK
+                trigger_walt_reboot reboot
+            fi
+        fi
+
+        # start /bin/blink [0|1] when we receive BLINK [0|1]
+        if [ "$req" = "BLINK" ]; then
+            if chroot "$final_root" [ -x "/bin/blink" ]; then
+                cd "$final_root"
+                if chroot . bin/blink $args; then
+                    # all is fine
+                    echo OK
+                else
+                    # /bin/blink apparently failed
+                    echo KO $MSG_BLINK_FAILED
+                fi
+                cd -
+            else
+                # no /bin/blink on this image
+                echo KO $MSG_NO_BLINK_EXEC
+            fi
+        fi
+
+        # if not in mode "multi", stop the loop.
+        # this will close nc's stdin thus stop it,
+        # and we will restart the whole thing because
+        # of the outer loop.
+        if [ "$mode" != "multi" ]; then break; fi
+    done
+}
+
+
+while true
 do
-    # respond to server if it checks whether we are alive
-    [ "$req" = "PING" ] && {
-        echo OK >&6
+    {
+        _handle_one_connection
+    } <$fifo_server_to_node | {
+        busybox nc -l -p 12346 >$fifo_server_to_node || true
     }
-    # respond to DMESG requests
-    [ "$req" = "DMESG" ] && {
-        echo OK >&6
-        echo >&6
-        busybox dmesg >&6
-    }
-    # respond to SHELL requests
-    [ "$req" = "SHELL" ] && {
-        echo OK >&6
-        echo >&6
-        busybox sh -i <&5 >&6 2>&1
-    }
-    # reboot the node when we receive REBOOT
-    [ "$req" = "REBOOT" ] && {
-        chroot "$final_root" [ -e "/bin/walt-reboot" ] && {
-            chroot "$final_root" [ -x "/bin/walt-reboot" ] && {
-                echo OK >&6
-                do_walt_reboot
-            } || {
-                echo KO $MSG_WALT_REBOOT_NO_EXEC >&6
-            }
-        } || {
-            echo OK >&6
-            reboot -f
-        }
-    }
-    # start /bin/blink [0|1] when we receive BLINK [0|1]
-    [ "$req" = "BLINK" ] && {
-        chroot "$final_root" [ -x "/bin/blink" ] && {
-            cd "$final_root"
-            chroot . bin/blink $args && {
-                # all is fine
-                echo OK >&6
-            } || {
-                # /bin/blink apparently failed
-                echo KO $MSG_BLINK_FAILED >&6
-            }
-            cd -
-        } || {
-            # no /bin/blink on this image
-            echo KO $MSG_NO_BLINK_EXEC >&6
-        }
-    }
+    echo "[bg] walt-net-service: restarting nc"
 done
 
