walt-init refactor for freebsd
Most importantly:
* possibility to redefine some functions used by walt-init
  (such as walt_mount, walt_umount) in a file
  [image-root]:/bin/walt-init-overrides which will be
  sourced by walt-init if present.
* There is now a single bg service handling both
  node up/down detection on server side and the handling
  of BLINK or REBOOT requests. Previously, there were
  two services called "walt-notify-bootup" and
  "walt-net-service". Now there is just "walt-net-service"
  which handles both features. The main benefit is
  that we got rid of the TCP server "walt-net-service"
  was previously starting. There is now just
  a single client connection node->server.
  The TCP server was providing debugging features
  such as a basic shell but it was hard to secure it
  on VPN nodes because not all busybox binaries provide
  the option to bind it to the walt-net interface IP:
  "busybox nc -l -s <local-ip> <port>".
  If we need these debugging features again, we could
  use a different mechanism, such as providing an empty
  file ".open-backdoor" in /persist or adding a node config
  option "debug.init.backdoor" which would cause an additional
  TCP server to be open.
* Both "walt-net-service" and "walt-fs-watchdog" are now
  run in the rootfs, and they chroot on the finalfs
  only temporarily when needed (e.g., to call /bin/blink).

diff --git a/server/walt/server/mount/walt-init b/server/walt/server/mount/walt-init
--- a/server/walt/server/mount/walt-init
+++ b/server/walt/server/mount/walt-init
@@ -1,42 +1,15 @@
 #!/bin/busybox sh
 
-# Check we are PID 1.
-if [ "$$" -ne 1 ]
-then
-    echo "This is the init script of walt nodes." >&2
-    echo "It is only useful when the node is booting. Exiting." >&2
-    exit 1
-fi
-
-MOUNT='busybox mount'
-UMOUNT='busybox umount'
 ROOTFS='/run/walt/rootfs'
-ROOTFS_BUSYBOX_APPLETS="
-    basename cat chroot cp date grep ln ls mkdir mkfifo mktemp modprobe
-    mount mv nc pivot_root reboot rm sed sh sleep timeout umount uname
+ROOTFS_EXECUTABLES="
+    basename cat chroot cp date grep ln ls mkdir mkfifo mktemp
+    mount mv nc reboot rm sed sh sleep timeout umount uname
 "
-ROOTFS_IMAGE_SCRIPTS="
-    /bin/walt-env
-    /bin/walt-log-tee
-    /bin/walt-log-cat
-    /bin/walt-log-echo
-    /bin/_walt_internal_/walt-fetch-node-config
-    /bin/_walt_internal_/walt-rpc
-    /bin/_walt_internal_/walt-clock-sync
-    /bin/_walt_internal_/walt-timeout
-    /bin/_walt_internal_/walt-boot-modes
-    /bin/_walt_internal_/walt-script-common
-    /bin/_walt_internal_/walt-init-rootfs
-    /bin/_walt_internal_/walt-init-rootfs-main
-    /bin/_walt_internal_/walt-init-disks
-    /bin/_walt_internal_/walt-init-finalfs
-    /bin/_walt_internal_/walt-init-nbd
-    /bin/_walt_internal_/walt-log-script
-    /bin/_walt_internal_/walt-fs-watchdog
-"
+
+. bin/_walt_internal_/walt-boot-modes  # needed for need_rw_nfsroot()
 
 _run_is_mounted() {
-    busybox mount | busybox grep " /run " >/dev/null
+    walt_mount | nostdout busybox grep " /run "
 }
 
 do_mounts()
@@ -47,14 +20,14 @@ do_mounts()
     then
         export had_procfs=1
     else
-        $MOUNT -t proc proc /proc
+        walt_mount -t proc proc /proc
         export had_procfs=0
     fi
     if [ -d "/sys/class" ]
     then
         export had_sysfs=1
     else
-        $MOUNT -t sysfs sysfs /sys
+        walt_mount -t sysfs sysfs /sys
         export had_sysfs=0
     fi
     # mount /dev and /run if missing.
@@ -62,123 +35,123 @@ do_mounts()
     # because walt bg processes need them.
     if [ ! -e "/dev/null" ]
     then
-        $MOUNT -t devtmpfs udev /dev
+        walt_mount -t devtmpfs udev /dev
     fi
     if ! _run_is_mounted
     then
-        $MOUNT -t tmpfs tmpfs /run
+        walt_mount -t tmpfs tmpfs /run
     fi
 }
 
-autodetect_block_modules() {
-    # we need to load at list the modules needed for block devices, and bus
-    # modules they are connected to (for hybrid boot modes).
-    # the original idea of looking into /sys/devices is borrowed from alpine's
-    # /etc/init.d/hwdrivers
-    busybox find /sys/devices/ -name modalias -type f -print0 2>/dev/null | \
-        busybox xargs -0 busybox sort -u | \
-        happy_grep -v \
-            "^\(\(acpi\)\|\(platform\)\|\(cpu\)\|\(serio\)\|\(dmi\)\|\(input\)\)"
-}
-
-# This function loads modules which we may need and may not be compiled in the kernel.
-load_modules() {
-    # crc32c may be needed for mounting ext4 filesystems without error (hybrid modes)
-    # nbd & zswap: useful for mounting a swap file stored remotely on server
-    # if other modules are needed, the image may provide a file /bin/walt-preinit
-    # to load them.
-    # note: "busybox modprobe" may cause dmesg warnings "Invalid ELF header magic"
-    # when dealing with compressed kernel modules, so we prefer the modprobe command
-    # provided by the OS if any.
-    modules="crc32c overlay overlayfs ext4 nfs nfsv3 nbd zswap"
-    more_modules=$(autodetect_block_modules)
-    run_busybox_or_not --prefer-system \
-        modprobe -a $modules $more_modules 2>/dev/null || true
-    # loading a bus module may uncover another module needed, so re-run autodetection
-    more_modules=$(autodetect_block_modules)
-    run_busybox_or_not --prefer-system \
-        modprobe -a $more_modules 2>/dev/null || true
-}
-
 preinit() {
-    if [ -e "/bin/walt-preinit" ]
+    if [ -x "/bin/walt-preinit" ]
     then
         boot_step_label_cr          "Calling /bin/walt-preinit..."
         /bin/walt-preinit
     fi
-}
-
-copy_exec_to_rootfs()
-{
-    exec_path="$(busybox which "$1")"
-    # copy binary
-    mkdir -p bin
-    cp "$exec_path" bin/
-    # check that ldd is available
-    if ! busybox which ldd >/dev/null
-    then
-        echo "Warning: no ldd -- If $1 is a dynamic executable," \
-             "this script will not work."
-        return
-    fi
-    # check needed shared libraries
-    if ! bin_deps="$(ldd "$exec_path" 2>/dev/null)"
-    then
-        # this executable is probably static, nothing more to do
-        return
-    fi
-    # copy shared libraries
-    echo "$bin_deps" | busybox awk '{print $(NF-1)}' | while read lib
-    do
-        if [ -f "$lib" ]
-        then
-            destdir="./$(dirname $lib)"
-            mkdir -p "$destdir"
-            cp "$lib" "$destdir"
-        fi
-    done
+    # call walt_preinit() optional function too,
+    # if defined in walt-init-overrides.
+    walt_preinit
 }
 
 prepare_rootfs()
 {
     busybox mkdir -p $ROOTFS
-    $MOUNT -t tmpfs tmpfs $ROOTFS  # pivot_root will need a mountpoint as <new_root>
+    # $ROOTFS must be a mountpoint for pivot_root() to work later
+    walt_mount -t tmpfs tmpfs $ROOTFS
     cd $ROOTFS
-    busybox mkdir -p tmp bin dev proc sys run mnt/nfsroot
+    busybox mkdir -p tmp bin mnt/nfsroot
     copy_exec_to_rootfs busybox
-    if busybox which nbd-client >/dev/null
+    if nostdout busybox which nbd-client
     then
         copy_exec_to_rootfs nbd-client
     fi
-    for image_script in $ROOTFS_IMAGE_SCRIPTS
+    for image_script in /bin/walt-* /bin/_walt_internal_/*
     do
         cp $image_script bin/
     done
-    for c in $ROOTFS_BUSYBOX_APPLETS
+    for c in $ROOTFS_EXECUTABLES
     do
-        ln -s busybox bin/$c
+        if [ ! -e bin/$c ]
+        then
+            if busybox_has_applet $c
+            then
+                ln -s busybox bin/$c
+            else
+                copy_exec_to_rootfs $c
+            fi
+        fi
     done
-    cd - >/dev/null
+    for fs_dir in proc sys dev run
+    do
+        ln -s mnt/nfsroot/$fs_dir $fs_dir
+    done
+    dump_walt_env > bin/walt-env
+    walt_populate_rootfs_custom
+}
+
+remount_nfsroot_if_needed()
+{
+    if need_rw_nfsroot
+    then
+        boot_step_label_cr "Ensuring the remote filesystem" \
+                           "is read-write..."
+        walt_mount -o remount,rw /
+    fi
+}
+
+mount_persistent() {
+    if [ -z "${walt_persist_path}" ]
+    then
+        echo "/persist was not mounted (cf. walt node config)"
+        return
+    fi
+    mkdir $ROOTFS/persist
+    walt_mount_persistent "$walt_persist_path" $ROOTFS/persist
+    # check if walt-init logs are enabled
+    walt_init_log_dir="$ROOTFS/persist/logs/walt-init"
+    if [ -d "$walt_init_log_dir" ]
+    then
+        # avoid NFS buffers by remounting with 'sync' option.
+        # note: "mount -o remount,sync" fails on some systems,
+        # so we umount + mount again.
+        walt_umount $ROOTFS/persist
+        walt_mount_persistent --sync "$walt_persist_path" $ROOTFS/persist
+    fi
 }
 
 switch_to_rootfs() {
     cd $ROOTFS
-    busybox pivot_root . mnt/nfsroot
-    exec busybox chroot . bin/walt-init-rootfs "$@" \
-        <mnt/nfsroot/dev/console \
-        >mnt/nfsroot/dev/console 2>&1
+    walt_switch_root_fs mnt/nfsroot \
+        bin/walt-init-rootfs "$@"
 }
 
 # let's go
 export PATH="$PATH:/bin/_walt_internal_"
 export walt_init_done=0
+# preparation work
 . walt-script-common
+# redefine console
+cd /; walt_set_console
+# run image's preinit code if any
+preinit
+# Check we are PID 1.
+if [ "$$" -ne 1 ]
+then
+    echo "This is the init script of walt nodes." >&2
+    echo "It is only useful when the node is booting. Exiting." >&2
+    exit 1
+fi
+# real start
 walt-log-echo "walt-init" "Starting up."
 boot_step_label_cr          "Initializing..."
 do_mounts
-load_modules
-preinit
-boot_step_label_cr          "Switching to rootfs..."
+walt_set_console  # in case do_mounts() just mounted /dev
+walt_load_kernel_modules
 prepare_rootfs
+boot_step_label_cr          "Mounting /persist..."
+mount_persistent
+remount_nfsroot_if_needed
+boot_step_label_cr          "Switching to rootfs..."
 switch_to_rootfs "$@"
 # the process continues in bin/_walt_internal_/walt-init-rootfs
diff --git a/server/walt/server/mount/walt-log-script b/server/walt/server/mount/walt-log-script
--- a/server/walt/server/mount/walt-log-script
+++ b/server/walt/server/mount/walt-log-script
@@ -3,10 +3,15 @@
 set +e  # if the subscript fails, we will handle the error
 
 mode="$1"
-log_dir="$2"
-script_name="$3"
-shift 3
+script_name="$2"
+shift 2
 script_args="$@"
+
+log_dir="/persist/logs/walt-init"
+if [ ! -d "$log_dir" ]
+then
+    log_dir=""
+fi
 
 # When logs are enabled, we want to monitor our shell scripts
 # by running them with 'sh -x' and redirecting stderr to a file
@@ -50,7 +55,7 @@ _logging_function() {
                     sh -x "$script_path" $script_args
                     echo $? >&5
                 } | busybox tee -a $log_file_base.out >&3
-            } 2>&1 | busybox tee -a $log_file_base.err >/dev/null
+            } 2>&1 | nostdout busybox tee -a $log_file_base.err
         } 5>&1)
         if [ "$res" != 0 ]
         then
@@ -73,7 +78,7 @@ _main() {
     result=$?
     if [ "$result" -ne 0 ]
     then
-        echo "$script_name returned with exit failure." >/dev/console
+        echo "$script_name returned with exit failure." >&2
         trigger_walt_reboot reboot
     fi
     allow_script_exit
diff --git a/server/walt/server/mount/walt-net-service b/server/walt/server/mount/walt-net-service
--- a/server/walt/server/mount/walt-net-service
+++ b/server/walt/server/mount/walt-net-service
@@ -1,50 +1,213 @@
 #!/bin/sh
 . walt-script-common
+MSG_NO_BLINK_EXEC='/bin/blink unavailable or not executable on image'
+MSG_BLINK_FAILED='/bin/blink returned a non-zero error code'
 
-# If needed the initramfs of an image may prepare
-# a script /run/nc-custom.sh for use instead of
-# "busybox nc".
-# Ex: VPN capable images use this to listen only
-# on the VPN interface, for security reasons.
-# Note: /run may be mounted with noexec, so
-# prefixing with "sh" is mandatory.
-if [ -e "/run/nc-custom.sh" ]
-then
-    nc_server="sh /run/nc-custom.sh -l -p 12346"
-else
-    nc_server="busybox nc -l -p 12346"
-fi
+# save stdout as fd 8
+# (because of the construct 'status=$(run_permanent_connection)' below)
+exec 8>&1
 
-# Unfortunately most versions of busybox do not provide nc server "-e" option
-# to start a handler command for each connexion, so we have to emulate this.
+wait_for_ssh() {
+    while [ 1 ]
+    do
+        # if port 22 is opened, send empty line to let sshd
+        # close the connection and let this nc command stop.
+        if nostdout nostderr walt-timeout 5 busybox nc 127.0.0.1 22 << EOF
 
-NC_FIFO="/run/walt/nc-$$-net.fifo"
-NC_FIFO_PID="/run/walt/nc-$$-net.pid"
-mkfifo $NC_FIFO
-mkfifo $NC_FIFO_PID
+EOF
+        then
+            break  # OK, port 22 is ready to accept connections
+        fi
+        busybox sleep 1
+    done
+}
 
-exec 4<>$NC_FIFO 5>&1 6<>$NC_FIFO_PID
+call_image_bootup_script() {
+    if [ -f "/mnt/finalfs/bin/on-bootup" ]
+    then
+        if [ -x "/mnt/finalfs/bin/on-bootup" ]
+        then
+            do_on_finalfs /bin/on-bootup
+        else
+            echo "WARNING: cannot run /bin/on-bootup (execute permission missing)." >&2
+        fi
+    fi
+}
 
+remove_nologin() {
+    busybox rm -f /mnt/finalfs/run/nologin
+}
+
+handle_blink() {
+    # start /bin/blink [0|1] when we receive BLINK [0|1]
+    shift  # ignore 1st arg "BLINK"
+    if [ -x "/mnt/finalfs/bin/blink" ]; then
+        if do_on_finalfs /bin/blink "$@" >&8; then
+            # all is fine
+            echo OK
+        else
+            # /bin/blink apparently failed
+            echo KO $MSG_BLINK_FAILED
+        fi
+    else
+        # no /bin/blink on this image
+        echo KO $MSG_NO_BLINK_EXEC
+    fi
+}
+
+handle_reboot() {
+    # reboot the node when we receive REBOOT
+    custom_script=$(get_custom_walt_reboot_script)
+    if [ ! -z "$custom_script" ]
+    then
+        # try to run it
+        if [ -x "/mnt/finalfs$custom_script" ]; then
+            echo OK
+            trigger_walt_reboot walt-custom-reboot $custom_script >&8
+        else
+            echo KO $custom_script is not executable on image
+        fi
+    else
+        echo OK
+        trigger_walt_reboot reboot >&8
+    fi
+}
+
+get_custom_walt_reboot_script() {
+    # custom rebooting is disabled for virtual nodes
+    # "walt_vnode_mode" was passed as an env variable
+    if [ "$walt_vnode_mode" -eq 1 ]
+    then
+        return
+    fi
+    if [ "${walt_boot_mode}" = "network-volatile" -o \
+         "${walt_boot_mode}" = "network-persistent" ]
+    then
+        # /bin/walt-network-reboot (new image)
+        if [ -e "/mnt/finalfs/bin/walt-network-reboot" ]; then
+            echo "/bin/walt-network-reboot"
+            return
+        fi
+        # legacy /bin/walt-reboot (old image)
+        if [ -e "/mnt/finalfs/bin/walt-reboot" ]; then
+            echo "/bin/walt-reboot"
+            return
+        fi
+    else    # hybrid boot
+        # /bin/walt-hybrid-reboot (new image)
+        if [ -e "/mnt/finalfs/bin/walt-hybrid-reboot" ]; then
+            echo "/bin/walt-hybrid-reboot"
+            return
+        fi
+        # note: hybrid boot is unknown for old images
+    fi
+}
+
+run_permanent_connection() {
+    nc_fifo="/tmp/net-service-$$.fifo"
+    [ -e $nc_fifo ] || mkfifo $nc_fifo
+    {
+        echo REQ_NODE_NET_SERVICE
+        # It is important to keep nc stdin open until we detect a
+        # disconnection, otherwise nc stops immediately.
+        while true
+        do
+            if msg=$(wait_for_input_line_shortly 20 < $nc_fifo)
+            then
+                case "$msg" in
+                    "STOP")
+                        break
+                        ;;
+                    "BLINK"*)
+                        handle_blink $msg
+                        ;;
+                    "REBOOT")
+                        handle_reboot
+                        ;;
+                    *)
+                        echo Unexpected "$msg" >&2
+                        break
+                        ;;
+                esac
+            else
+                # Some versions of busybox nc fail to stop when the
+                # remote end is closed. We send EOL chars periodically
+                # (i.e. if no other message to transmit for 20s)
+                # to detect this.
+                echo
+            fi
+        done
+    } | {
+        busybox nc $walt_server_ip $walt_server_notify_bootup_port || true
+    } | {
+        connected=0
+        # read OK from server within 3 seconds
+        if msg_ok=$(wait_for_input_line_shortly 3)
+        then
+            if [ "$msg_ok" = "OK" ]
+            then
+                connected=1
+                # Correct response obtained from server.
+                # We can now listen indefinitely on connection,
+                # and forward server requests (REBOOT, BLINK)
+                # on the fifo.
+                { cat; echo STOP; } > $nc_fifo
+                # cat will stop when its input is closed,
+                # i.e., when 'busybox nc' stops.
+            fi
+        fi
+        # let the caller know what happened
+        if [ $connected -eq 1 ]
+        then
+            # disconnection
+            echo DISCONNECTED
+        else
+            # connection failure, stop the loop above
+            echo STOP > $nc_fifo
+            echo CONNECT_FAILED
+        fi
+    }
+}
+
+echo "[walt:bg] walt-net-service started."
+
+# We consider the node is ready when its
+# sshd service is ready to accept connections.
+wait_for_ssh
+
+# call script /bin/on-bootup if image provides it
+call_image_bootup_script
+
+# remove /run/nologin if present
+# (if present a warning message may be printed when connecting
+# very early and the OS considers bootup procedure is not complete)
+remove_nologin
+
+# save uptime to know when the OS got ready
+[ ! -e /run/uptime-ready ] && cp /proc/uptime /run/uptime-ready
+
+# we maintain a permanent connection to walt server.
+# opening it will set our status to "booted".
+# if this connection is closed on our side, the server
+# can detect we are down. if this connection is closed
+# on server side, we know that the server is down and
+# images are probably umounted, so we reboot.
+retries=2
 while true
 do
-    {
-        $nc_server <&4 &
-        nc_pid=$!
-        echo $nc_pid >&6
-        wait $nc_pid
-    } | {
-        read nc_pid <&6
-        # block until we get a first line before starting walt-net-service-handler
-        # (because walt-net-service-handler handles a timeout)
-        read first_line
-        {
-            echo "$first_line"
-            cat
-        } | {
-            walt-net-service-handler
-            sleep 1 # ensure nc has time to flush everything
-            kill $nc_pid 2>/dev/null || true
-            echo "[walt:bg] walt-net-service: restarting nc" >&5
-        }
-    } >&4
+    status=$(run_permanent_connection)
+    # in rare cases a TCP connection may fail, so we must try
+    # a few times.
+    if [ "$status" = "CONNECT_FAILED" -a $retries -gt 0 ]
+    then
+        retries=$((retries - 1))
+        echo "[walt:bg] walt-net-service: reconnecting attempt after 5 seconds"
+        busybox sleep 5
+        continue
+    else
+        echo "[walt:bg] walt-net-service:" \
+             "failed or lost connection to walt server!" >&2
+        busybox sleep 3
+        trigger_walt_reboot reboot
+    fi
 done
diff --git a/server/walt/server/mount/walt-script-common b/server/walt/server/mount/walt-script-common
--- a/server/walt/server/mount/walt-script-common
+++ b/server/walt/server/mount/walt-script-common
@@ -1,8 +1,6 @@
 #!/bin/sh
 
-# all scripts sourcing this file get the env variables
-# and have error monitoring enabled:
-. walt-env
+# all scripts sourcing this file have error monitoring enabled:
 set -e
 trap _on_exit EXIT
 
@@ -13,7 +11,7 @@ _emergency_reboot() {
     set +e
     cd /
     echo "emergency reboot"
-    busybox umount -a
+    walt_umount -a
     busybox reboot -f now
 }
 
@@ -35,7 +33,7 @@ _admin_sh()
 _detect_input() {
     echo '>>> Issue detected!               <<<'
     echo 'Will reboot... (or press <ENTER> now for a shell)'
-    wait_for_input_line_shortly 5 >/dev/null 2>&1
+    nostdout wait_for_input_line_shortly 5
 }
 
 _reboot_or_sh()
@@ -119,33 +117,116 @@ _do_reboot() {
         # we have booted on a local disk, or with a read-write NFS overlay,
         # let the init system follow its shutdown procedure.
         echo "Calling 'reboot' command." >&2
-        if walt-timeout $REBOOT_CMD_TIMEOUT $(which reboot)
+        if do_on_finalfs walt-timeout $REBOOT_CMD_TIMEOUT reboot
         then
             # the OS should now be shutting down its services
             _wait_for_os_shutdown
         else
-            echo "'reboot' command failed!" >&2
-            exit 1
+            echo "'reboot' command failed, forcing reboot!" >&2
+            _do_force_reboot
         fi
     fi
 }
 
 _do_walt_reboot() {
     script="$1"
-    WALT_REBOOT_CMD_TIMEOUT=60  # walt-reboot has to download a kernel, initrd, etc.
+    # walt-reboot has to download a kernel, initrd, etc.
+    WALT_REBOOT_CMD_TIMEOUT=60
     echo "Calling $script"
-    if walt-timeout $WALT_REBOOT_CMD_TIMEOUT $script >/dev/null 2>/dev/null
+    if nostdout nostderr do_on_finalfs \
+            walt-timeout $WALT_REBOOT_CMD_TIMEOUT $script
     then
         # the OS should now be shutting down its services
         _wait_for_os_shutdown
     else
-        echo "Command 'bin/walt-reboot' failed!" >&2
+        echo "Command '$script' failed!" >&2
         _do_force_reboot
     fi
 }
 
+# if we lose nfsroot we will not be able to reach /dev/null
+# because /dev is a symlink to mnt/nfsroot/dev in the rootfs.
+# so let's open the file in advance, as soon as we can.
+
+_open_null_if_not_done_yet() {
+    if [ -z "$_null_opened" ]
+    then
+        if [ -e "/dev/null" ]
+        then
+            exec 9>/dev/null
+            export _null_opened=1
+        else
+            return 1
+        fi
+    fi
+}
+
+_open_null_if_not_done_yet || true
+
+_init_walt_env() {
+    if [ -z "$walt_env" ]
+    then
+        export walt_env="$(
+            cat /bin/walt-env
+            /bin/_walt_internal_/walt-fetch-node-config
+        )"
+        eval "$walt_env"
+    fi
+}
+
+_init_walt_env
+
 # public functions
 # ################
+
+nostdout() {
+    if _open_null_if_not_done_yet
+    then
+        "$@" >&9
+    else
+        echo "warning: nostdout ignored, /dev/null is not available" >&2
+        "$@"
+    fi
+}
+
+nostderr() {
+    if _open_null_if_not_done_yet
+    then
+        "$@" 2>&9
+    else
+        echo "warning: nostderr ignored, /dev/null is not available" >&2
+        "$@"
+    fi
+}
+
+update_walt_env() {
+    prop=$1
+    value=$2
+    export walt_env="$(
+        echo "$walt_env" | sed -e "s/\($prop\).*/\1=$value/"
+    )"
+    export $prop=$value
+}
+
+dump_walt_env() {
+    echo "$walt_env"
+}
+
+do_on_finalfs() {
+    cd /mnt/finalfs
+    # take into account the fact several calls to do_on_finalfs()
+    # may occur (e.g., for blink), and umounting may have failed
+    # on a previous call.
+    [ -e dev/null ] || walt_mount -o bind /dev dev
+    [ -e proc/self ] || walt_mount -o bind /proc proc
+    [ -e run/walt ] || walt_mount -o bind /run run
+    busybox chroot . "$@" || retcode=$?
+    [ ! -e dev/null ] || nostderr walt_umount dev || true
+    [ ! -e proc/self ] || nostderr walt_umount proc || true
+    [ ! -e run/walt ] || nostderr walt_umount run || true
+    nostdout cd -
+    return $retcode
+}
 
 happy_grep() {
     grep "$@" || true   # always return status ok
@@ -171,26 +252,7 @@ trigger_walt_reboot() {
 }
 
 wait_for_input_line_shortly() {
-    walt-timeout $1 busybox sh -c 'read l && echo "$l"'
-}
-
-mount_union()
-{
-    lowerdir="$1"
-    upperdir="$2"
-    workdir="$3"
-    uniondir="$4"
-
-    # creating the union
-    # /: the nfs mount (that should remain read-only)
-    # fs_rw: the place to hold the filesystem changes
-    # finalfs: the mount point of the union
-    busybox mount -t overlay \
-        -o upperdir=${upperdir},lowerdir=${lowerdir},workdir=${workdir} \
-        union ${uniondir} 2>/dev/null || \
-    busybox mount -t overlayfs \
-        -o upperdir=${upperdir},lowerdir=${lowerdir} \
-        union ${uniondir}
+    nostderr walt-timeout $1 busybox sh -c 'read l && echo "$l"'
 }
 
 boot_step_label_cr() {
@@ -198,7 +260,7 @@ boot_step_label_cr() {
 }
 
 busybox_has_applet() {
-    busybox $1 --help >/dev/null 2>&1
+    nostdout nostderr busybox $1 --help
 }
 
 run_busybox_or_not() {
@@ -206,7 +268,7 @@ run_busybox_or_not() {
     if [ "$1" = "--prefer-system" ]
     then
         shift
-        cmd="$(busybox which "$1")" || cmd="busybox $1"
+        cmd="$(notsderr busybox which "$1")" || cmd="busybox $1"
     else
         if busybox_has_applet "$1"
         then
@@ -236,3 +298,145 @@ possibly_vpn_node() {
         echo 1
     fi
 }
+
+copy_exec_to_rootfs()
+{
+    exec_path="$(busybox which "$1")"
+    # copy binary
+    mkdir -p bin
+    cp "$exec_path" bin/
+    # check that ldd is available
+    if ! nostdout busybox which ldd
+    then
+        echo "Warning: no ldd -- If $1 is a dynamic executable," \
+             "this script will not work."
+        return
+    fi
+    # check needed shared libraries
+    if ! bin_deps="$(nostderr ldd "$exec_path")"
+    then
+        # this executable is probably static, nothing more to do
+        return
+    fi
+    # copy shared libraries
+    echo "$bin_deps" | busybox awk '{print $(NF-1)}' | while read lib
+    do
+        if [ -f "$lib" ]
+        then
+            destdir="./$(dirname $lib)"
+            mkdir -p "$destdir"
+            cp "$lib" "$destdir"
+        fi
+    done
+}
+
+autodetect_block_modules() {
+    # we need to load at list the modules needed for block devices, and bus
+    # modules they are connected to (for hybrid boot modes).
+    # the original idea of looking into /sys/devices is borrowed from alpine's
+    # /etc/init.d/hwdrivers
+    nostderr busybox find /sys/devices/ -name modalias -type f -print0 | \
+        busybox xargs -0 busybox sort -u | \
+        happy_grep -v \
+            "^\(\(acpi\)\|\(platform\)\|\(cpu\)\|\(serio\)\|\(dmi\)\|\(input\)\)"
+}
+
+# default functions, overridable in [image-root]:/bin/walt-init-overrides
+# -----------------------------------------------------------------------
+walt_load_kernel_modules() {
+    # This function loads modules which we may need and may not be compiled
+    # in the kernel.
+    # crc32c may be needed for mounting ext4 filesystems without error
+    # (hybrid modes).
+    # nbd & zswap: useful for mounting a swap file stored remotely on server.
+    # if other or different modules are needed, the image may override this
+    # function in its walt-init-overrides file.
+    # note: "busybox modprobe" may cause dmesg warnings "Invalid ELF header magic"
+    # when dealing with compressed kernel modules, so we prefer the modprobe command
+    # provided by the OS if any.
+    modules="crc32c overlay overlayfs ext4 nfs nfsv3 nbd zswap"
+    more_modules=$(autodetect_block_modules)
+    nostderr run_busybox_or_not --prefer-system \
+        modprobe -a $modules $more_modules || true
+    # loading a bus module may uncover another module needed, so re-run autodetection
+    more_modules=$(autodetect_block_modules)
+    nostderr run_busybox_or_not --prefer-system \
+        modprobe -a $more_modules || true
+}
+
+walt_mount() {
+    busybox mount "$@"
+}
+
+walt_umount() {
+    busybox umount "$@"
+}
+
+walt_switch_root_fs() {
+    put_old="$1"
+    shift 1
+    # notes:
+    # - current dir will become the new root.
+    # - the old root (current one) will be mounted at $put_old
+    busybox pivot_root . "$put_old"
+    # switch to dev/console to release /dev
+    walt_set_console
+    # run specified command
+    exec busybox chroot . "$@"
+}
+
+walt_populate_rootfs_custom() {
+    # by default, nothing more to do
+    true
+}
+
+walt_preinit() {
+    # by default, nothing to do
+    true
+}
+
+walt_set_console() {
+    [ -e "dev/console" ] && exec <"dev/console" >"dev/console" 2>&1
+}
+
+# Mounting /persist, for storing persistent data even across reboots.
+# Data are stored on the server through an NFS share.
+walt_mount_persistent()
+{
+    options="rw,relatime,vers=3,nolock"
+    if [ "$1" = "--sync" ]
+    then
+        options="${options},sync"
+        shift
+    fi
+
+    # Mount the share
+    walt_mount -t nfs -o "$options" "$1" "$2"
+}
+
+walt_mount_union()
+{
+    lowerdir="$1"
+    upperdir="$2"
+    workdir="$3"
+    uniondir="$4"
+
+    # creating the union
+    # lowerdir: the nfs mount (that should remain read-only)
+    # upperdir: the place to hold the filesystem changes
+    # workdir: useful to let the filesystem implement atomic
+    #          operations properly
+    # uniondir: the mount point of the union
+    nostderr walt_mount -t overlay \
+        -o upperdir=${upperdir},lowerdir=${lowerdir},workdir=${workdir} \
+        union ${uniondir} || \
+    walt_mount -t overlayfs \
+        -o upperdir=${upperdir},lowerdir=${lowerdir} \
+        union ${uniondir}
+}
+
+# apply image overrides if provided
+if [ -e /bin/walt-init-overrides ]
+then
+    . /bin/walt-init-overrides
+fi
