wip -- walt init
- check if it still boots with all nodes vn0, vn-freebsd, clipperton
- check boot modes
- check walt node save
- check persist
- check kexec reboot on clipperton (w/ linux image)

diff --git a/server/walt/server/mount/walt-init-disks b/server/walt/server/mount/walt-init-disks
--- a/server/walt/server/mount/walt-init-disks
+++ b/server/walt/server/mount/walt-init-disks
@@ -6,6 +6,11 @@ detect_partition_devices() {
     # For each disk we have:
     # - an entry /sys/class/block/<disk>/device/
     # - one entry /sys/class/block/<disk>/<partition>/ for each partition
+    if [ ! -d /sys/class/block/ ]
+    then
+        echo "Bypassed, /sys/class/block directory is missing." >&2
+        return 1
+    fi
     cd /sys/class/block/
     nostderr ls -1 */*/dev | {
         IFS="/"
